### ISSUE TITLE
Bound box is sometimes partially formed

### ISSUE THREAD

**Issue by salmaashraf2000** [cansik/yolo-hand-detection#20]
![Photos 2_8_2022 5_46_30 PM](https://user-images.githubusercontent.com/57508222/153024809-358bac38-4ca7-4587-b90e-75c51ebdd4cc.png)
I have used your model for detecting on my own photos but sometimes the box is not completed like in the attached photo 
what can I do?
also few times hands are not recognized, what processing can I do to solve this case? 
Thanks a lot for this effort

**Comment by cansik** [comment]
I guess this is because the [rectangle annotating](https://github.com/cansik/yolo-hand-detection/blob/42d038bbc5deed14b11b27a871ca4385b4d880a2/demo.py#LL69C60-L69C60) the hand bounding box has a line-thickness of 1. Increase it and this should not happen anymore.

The detection is not great, today I would use something like [Mediapipe Hands](https://google.github.io/mediapipe/solutions/hands.html) for hand detection.
